services:
  traefik:
    image: traefik:v3.2
    command:
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--api.dashboard=true'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--entryPoints.web.http.redirections.entryPoint.to=websecure'
      - '--entryPoints.web.http.redirections.entryPoint.scheme=https'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=marcus.marinelli3@gmail.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - letsencrypt:/letsencrypt

  app:
    image: ghcr.io/mgm103/personal-portfolio:${GIT_COMMIT_HASH:-latest}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`marcusmarinelli.com`)'
      - 'traefik.http.routers.app.entryPoints=websecure'
      - 'traefik.http.routers.app.tls.certresolver=myresolver'
      - 'traefik.http.services.app.loadbalancer.server.port=3000'
    environment:
      - ORIGIN=https://marcusmarinelli.com
    deploy:
      update_config:
        order: start-first

volumes:
  letsencrypt:
