services:
  app:
    image: ghcr.io/mgm103/personal-portfolio:${GIT_COMMIT_HASH:-latest}
    container_name: personal-portfolio-site
    environment:
      - ORIGIN=https://marcusmarinelli.com
    ports:
      - '3000:3000'
    deploy:
      update_config:
        order: start-first
